### PR TITLE
Update UserStatus Enum to include DEACTIVATED User

### PR DESCRIPTION
**Pull request by raviprajna**
Smartsheet admin centre allows sys admin to deactivate user, but the UserModel do not support this new value which is causing serialisation exception when we try to pull all the users and deserialise them. There is also no way filter out deactivated users while requesting list-user rest api. So we are blocked and cannot load our UserManagement Page.

### CODE REVIEW

**Comment by Nerfix** [comment]
Do we need to add new endpoints to the SDK or update existing ones? Is adding the enum sufficient?

**Comment by DonoA** [comment]
Hey Nerfix, as long as the API has been updated to return `DEACTIVATED` for the user status enum, it will be picked up without any modification to the endpoints.

**Comment by Nerfix** [comment]
@raviprajna Can you update the tests?

@DonoA That makes sense. We may want to add support for deactivating a user through the SDK going forward.

**Comment by abduganio** [comment]
@Nerfix @DonoA Updated the UserStatusTest to include the new DEACTIVATED status. 
Can i please get a review on these changes?

**Review by zromano — APPROVED** [review]

**Pull request merged**
